apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  labels:
    app: springboot-metrics
  name: springboot-metrics-component
spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: springboot-metrics-workload
      labels:
        app: springboot-metrics
        version: v1
    spec:
      selector:
        matchLabels:
          app: springboot-metrics
      template:
        metadata:
          labels:
            app: springboot-metrics
        spec:
          containers:
            - name: springboot-metrics-container
              image: springboot-metrics:latest
              imagePullPolicy: Never
              ports:
                - containerPort: 8080
                  name: metrics